<ProductEntryWidget>:
    cols: 3

    Label:
        id: product_name
        font_size: min(self.height/3, self.width/8)

    TextInput:
        id: product_price
        multiline: False
        font_size: min(self.height/2, self.width/8)
        text_size: self.size

        foreground_color: (1, 0, 0, 1) if self.text == "0.00" else (0, 0, 0, 1)

    PersonSelectionWidget:
        id: selection_widget